### ISSUE TITLE
MIDI output devices aren't stored in the plugdata.settings file

### ISSUE THREAD

**Issue by agraef** [plugdata-team/plugdata#1004]
MIDI output settings aren't remembered across invocations. This is with current HEAD from the develop branch, running on Linux, but it's the same in 0.7.0, so I don't think that this ever worked.

If I enable an output device, the state is shown alright in the MIDI setup if I reinvoke the dialog later. But if I exit the program, the MIDI output devices aren't written to the plugdata.settings and thus all MIDI output devices are disabled when launching plugdata again. (Except the internal GM synth. But that setting seems to live elsewhere, at least I don't see it in plugdata.settings.) Here's the relevant section from my plugdata.settings file:

~~~xml
  <VALUE name="audioSetup">
    <DEVICESETUP deviceType="ALSA" audioOutputDeviceName="JACK Audio Connection Kit"
                 audioInputDeviceName="JACK Audio Connection Kit" audioDeviceRate="48000.0"
                 audioDeviceInChans="11" audioDeviceOutChans="11">
      <MIDIINPUT name="APC mini mk2 APC mini mk2 Contr" identifier="24-0"/>
      <MIDIINPUT name="MPK mini Plus MIDI 1" identifier="40-0"/>
      <MIDIINPUT name="mioXM DIN 1" identifier="48-0"/>
    </DEVICESETUP>
  </VALUE>
~~~

Maybe that's a JUCE limitation? I see code for the `MIDIINPUT` tag in the JUCE source, but nothing concerning MIDI outputs as far as I can tell.

**Comment by agraef** [comment]
> Except the internal GM synth. But that setting seems to live elsewhere

Yep. This is stored in InternalSynthToggle:valueChanged():

~~~c++
processor->settingsFile->setProperty("internal_synth", static_cast<int>(processor->enableInternalSynth));
~~~

So this isn't affected by the total amnesia of the output devices. Maybe something similar needs to be done for the other output devices to have them remembered.

**Comment by timothyschoen** [comment]
Yes, the reason why MidiInputs are saved and MidiOutputs are not, is that MidiInputs are handled by JUCE internally in AudioDeviceManager. However, AudioDeviceManager only has support for a single MIDI output, so that's why MIDI outputs are implemented manually. I'll write something to make it remember the outputs too.

**Comment by timothyschoen** [comment]
Should be fixed on HEAD

**Comment by agraef** [comment]
Nice, many thanks!

But suddenly, I can't select the audio device any more. When trying to switch from ALSA audio to Jack, the program freezes and I have to kill it. Maybe there's something wrong with rev. a8ae939aca4dc7d8cb5cc2a9565822957e24fe86?

**Comment by agraef** [comment]
Yep, https://github.com/plugdata-team/plugdata/commit/a8ae939aca4dc7d8cb5cc2a9565822957e24fe86 is the culprit. After reverting it, everything is back to normal.

**Comment by agraef** [comment]
Also, there's still a problem with the wrong output device being enabled if a device disappeared between invocations. I guess that's because you store the device identifiers instead of their names in the persistent configuration data. That makes it easier to implement, but those identifiers are subject to change between different invocations of the application, e.g., when an application with an ALSA MIDI port such as qsynth is closed, or a MIDI device is unplugged. The identifiers really keep changing all the time, at least on Linux; JUCE only keeps them stable while the app is running. That's why I think we have not other choice but to store the device names instead, and map these to the identifiers when reinitializing the output devices. I can send you a PR for that, stay tuned.

**Comment by agraef** [comment]
But #1014 is for real, this fixes the device naming issue described above. Also, I've submitted #1013 to fix the issue with the CI workflow using all kinds of secrets which a fork may not have, making builds fail or display strange errors in the build logs. #1013 fixes these, but you still need to test that my changes don't break the workflow in your repo. (I'm pretty sure that it should still work, but I can't check it until you merge that PR.)
