### ISSUE TITLE
Bug - erroneous control of output midi ports in [midiout],[noteout], [pgmout], [ctlout] (0.8.0)

### ISSUE THREAD

**Issue by KPY7030P** [plugdata-team/plugdata#1210]
https://github.com/plugdata-team/plugdata/assets/22715416/21d5cb34-bf99-4087-a9ee-841170324d5c
**the first video** demonstrates that the virtual midi ports are working properly. they transmit signals as expected. It is also shown that when sending the number 0 or 1 to the object-[midiout] to the right input, the signals are sent simultaneously to all devices-(virtual midi ports). When sending the number 2 to the object at the right input (i.e. installing the second port in the object), the useful signals go only to the first virtual port.  When sending the number 3 to the object at the right input, the signals go only to the second virtual port. 
It is natural to expect that when receiving the number 4, the [midiout] object will send the received signals to the third port. However, the signals are not sent anywhere. 
{it is logical to assume that to select all output ports, it is worth using the number zero at the right input of the [midiout] object, 
and then the numbers 1-N should denote each device individually}

>---------
https://github.com/plugdata-team/plugdata/assets/22715416/52f08dee-f097-4045-9707-c253a2658c80
**The second video** shows a similar situation with the [noteout] object. In this object, the selection of the device-(virtual midi port) is carried out by switching channels 1-16 channels =1 port 17-32 channels = 2port and so on. However, no signals are sent when the third virtual port is reached. In this case, the start of the third virtual port was expected on channel 49. In the case of the [midiout] object, it was expected that it would work when switching to port 4.

>---------
https://github.com/plugdata-team/plugdata/assets/22715416/b292785b-8bbd-451f-96a4-ca094b36ed7b
**The third video** shows the same situation with the [noteout] object, but already when using a manual selection of the device and port using a double-click and a drop-down menu. In general, this is no different from the second video. The third device does not receive signals by default if it is forcibly selected in this way. 

But there is one more detail that is important. A total of 16 channels per port are supported. However, there are **_only 15 channels_** in the selection menu. Most likely, you need to start from scratch, or continue this list to 16. 

>---------
https://github.com/plugdata-team/plugdata/assets/22715416/d339097a-68f3-4dc6-9ab8-2025d7d06603
**The fourth video** demonstrates a very important feature that shows that sending messages is not limited to three devices - (virtual midi ports or real equipment) . This video shows that no matter how many devices there are, the last one will not receive messages. I assume that this is due to the displacement of the entire list of devices, since when the zero port of the object is set (sending the number 0 to the right input of the object [midiout] or selecting 1-16 channels in the object [noteout]), messages are sent to all devices
Setting the first port (sending the number 1 to the right input of the object [midiout]) gives the same results and causes signals to be sent to all devices.
>---------

Patch for tests:
[midiOutObjProblems1.zip](https://github.com/plugdata-team/plugdata/files/12837718/midiOutObjProblems1.zip)

**Comment by RomaRogov** [comment]
I also have difficulties with this. I would like to set up my midi outputs for external synthesizers, but not all of them work as they should. I also noticed that there are only fifteen channels, not sixteen. It's not critical for me, but I think it might be important to someone.

**Comment by timothyschoen** [comment]
I think this is fixed on the latest nightly build, could you verify this?

Download this one: https://github.com/plugdata-team/plugdata/actions/runs/6518488539

**Comment by KPY7030P** [comment]
Unfortunately, the last nightly builds for Windows ended in failure.

**Comment by timothyschoen** [comment]
Oops, fixed that

**Comment by KPY7030P** [comment]
Now there are 16 channels in the drop-down menu, but all the other problems remain. I will run some more tests, reinstalling the program to a clean one, and then I will write the results soon.

**Comment by KPY7030P** [comment]
I checked the build "e62c368a" on windows 10 and unfortunately there were problems with the last midi port. The problem persists when selecting from the menu and by sending the port number.channel to object

**Comment by timothyschoen** [comment]
> I checked the build "e62c368a" on windows 10 and unfortunately there were problems with the last midi port. The problem persists when selecting from the menu and by sending the port number.channel to object

Cool, so only problems when using the last port? I'll see why that is

**Comment by timothyschoen** [comment]
Fixed that too! I think this is all fixed now then?

**Comment by KPY7030P** [comment]
> Fixed that too! I think this is all fixed now then?

Hi! Due to the fact that I was out of town, and the fact that some nightly builds ended with an error for Windows x64, I was only able to test it now. At present, the last of the midi ports works with any number of ports. 
But I don't quite understand the logic of port numbering. For the [midiout] object, sending to the first port begins when the "2" message is sent to this object. For objects [pgmout], [ctlout ], [noteout], the first port starts when the message "17" is sent to this object instead of "1".  
Maybe there is some logic in this that I can't understand? :)

**Comment by timothyschoen** [comment]
Hmm maybe it's still not completely correct. I'll reopen for now and check it out later!

**Comment by KPY7030P** [comment]
Hi! I think I have some problems again. Now I can't switch to any individual midi port in the [midiout] object. Signals are sent to all ports simultaneously.
I tried installing "Nightly build: 279276"

https://github.com/plugdata-team/plugdata/assets/22715416/e3ef57dd-1dc7-4b9d-bb23-5182984e2098

But I think I understood why to select the first port in [noteout] it is necessary to send signals "17-32" to this object instead of "1-16". The fact is that "1-16" are channels for all devices at the same time. Then there are channels for individual devices.
