### ISSUE TITLE
takes a lot of time to load the patch when loading soundfile via [player~]

### ISSUE THREAD

**Issue by H-MLim** [plugdata-team/plugdata#2085]
![Image](https://github.com/user-attachments/assets/24f74680-520b-408d-b8de-ca8852384c8f)

hi. I thought when I try to load my patch, the whole console freezes and crashes (both when load by clicking windows on the main console, and load from the menu, and also click and load patch file directly). but actually it takes very long time to load it, and I had to wait about 2~3 minutes. this happened on Nightly build: 3ddb5db09, Win11.

also this crashes by loading already-saved patches. but it was OK when creating new patch, save, and load.

**Comment by timothyschoen** [comment]
Could you share the patch that makes this happen?

**Comment by H-MLim** [comment]
[clock-player.zip](https://github.com/user-attachments/files/19072242/clock-player.zip)

hi. here is the patch. could this be help?

**Comment by timothyschoen** [comment]
Thanks, 070187d8a should fix it :)

**Comment by H-MLim** [comment]
hmm sorry I'm afraid it doesn't work for me. could you check once more?

**Comment by timothyschoen** [comment]
https://github.com/user-attachments/assets/a8293131-499c-40fe-a9d6-7d21201dcaa8

Testing on Windows now, load pretty much instantly. Could you try reinstalling the nightly? Maybe something went wrong with the installer?

**Comment by H-MLim** [comment]
that's strange. I deleted all my data of plug on my computer - deleting plug both in Program Files and Appdata\Roaming\plugdata - redownloaded the installer, and reinstalled again. but same issue persists on my computer 🤔

https://github.com/user-attachments/assets/6abc6011-77ea-48e7-b93e-c640e6a0fe29

**Comment by H-MLim** [comment]
I believe it's fixed in Nightly build: 7df2302fb!

**Comment by H-MLim** [comment]
oh hi. I think what was the problem. the thing is, the patch loads very longer when loading bigger wav. file from `player~`. could you test this patch (with soundfile)? do you still can load it instantly?

**Comment by H-MLim** [comment]
this still happens on both the vanilla, stable 0.9.3 and nightly 0.9.4 (also on vanilla 0.56-5). I suggest you to reopen the issue

**Comment by porres** [comment]
@timothyschoen help me with this one? :)

**Comment by H-MLim** [comment]
also related: just in case https://github.com/porres/pd-else/issues/2648
