### ISSUE TITLE
open on load flag for subpatches

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#872]
i know this is for later, but wanted to leave it here

given this patch:

[subpatches.pd.txt](https://github.com/plugdata-team/plugdata/files/11424861/subpatches.pd.txt)

saved on parent
```
#N canvas 827 239 527 327 12;
#N canvas 0 50 450 300 hi 1;
#N canvas 0 50 450 300 hello 0;
#N canvas 0 50 450 300 hiiiiiiiiiiiiiiiiiiiiii 0;
#N canvas 0 50 450 300 do 0;
#X restore 139 129 pd do crimes;
#X restore 169 129 pd hiiiiiiiiiiiiiiiiiiiiii;
#X restore 167 123 pd hello;
#X restore 179 139 pd hi;
```
opened hi and saved
```
#N canvas 827 239 527 327 12;
#N canvas 0 50 450 300 hi 1;
#N canvas 0 50 450 300 hello 1;
#N canvas 0 50 450 300 hiiiiiiiiiiiiiiiiiiiiii 0;
#N canvas 0 50 450 300 do 0;
#X restore 139 129 pd do crimes;
#X restore 169 129 pd hiiiiiiiiiiiiiiiiiiiiii;
#X restore 167 123 pd hello;
#X restore 179 139 pd hi;
```
opened hi -> hello then saved
```
#N canvas 827 239 527 327 12;
#N canvas 0 50 450 300 hi 1;
#N canvas 0 50 450 300 hello 1;
#N canvas 0 50 450 300 hiiiiiiiiiiiiiiiiiiiiii 1;
#N canvas 0 50 450 300 do 0;
#X restore 139 129 pd do crimes;
#X restore 169 129 pd hiiiiiiiiiiiiiiiiiiiiii;
#X restore 167 123 pd hello;
#X restore 179 139 pd hi;
```
and so on

so  as long as a subpatch has been opened, all its children have open-on-load flag.. it makes reading diffs really difficult, i have to save, then close patch, then open it and then save it without opening anything

**Comment by timothyschoen** [comment]
Fixed with a6a72ca53a2c0af65061c6fcd2668bf40a81c30a

**Comment by tomara-x** [comment]
holy shit! thank you!

**Comment by tomara-x** [comment]
this had a regression at some point, but it only happens with graphs (not normal subpatches)

take this patch as an example (this is saved with only the main patch open)

```
#N canvas 827 239 527 327 12;
#N canvas 0 0 450 250 (subpatch) 1;
#N canvas 0 0 450 250 (subpatch) 1;
#X coords 0 1 100 -1 200 140 1 0 0;
#X restore 331 214 graph;
#X coords 0 1 100 -1 200 140 1 0 0;
#X restore 274 185 graph;
```

opening the same patch in vanilla and keeping only the main window open, then saving it gives you this output:

```
#N canvas 316 321 527 327 12;
#N canvas 0 0 450 250 (subpatch) 0;
#N canvas 894 323 450 250 (subpatch) 0;
#X coords 0 1 100 -1 200 140 1 0 0;
#X restore 331 214 graph;
#X coords 0 1 100 -1 200 140 1 0 0;
#X restore 274 185 graph;

```

discovered here: https://github.com/tomara-x/moths/pull/2

@alcomposer you forgot to reopen this :p
